## Read and understand the Data

In [ ]:
data = "/home/slark/DE-projects/Commercial-data/super_store/data/store_data.csv"

In [4]:
pip install pandas

Requirement already satisfied: pandas in /home/slark/DE-projects/Commercial-data/super_store/venv/lib/python3.13/site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in /home/slark/DE-projects/Commercial-data/super_store/venv/lib/python3.13/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/slark/DE-projects/Commercial-data/super_store/venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/slark/DE-projects/Commercial-data/super_store/venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv(data)

In [7]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,01/01/2011,06/01/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,01/01/2011,08/01/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,01/01/2011,05/01/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,01/01/2011,05/01/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,01/01/2011,08/01/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [8]:
df.shape

(51290, 21)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  str
 1   order_date      51290 non-null  str
 2   ship_date       51290 non-null  str
 3   ship_mode       51290 non-null  str
 4   customer_name   51290 non-null  str
 5   segment         51290 non-null  str
 6   state           51290 non-null  str
 7   country         51290 non-null  str
 8   market          51290 non-null  str
 9   region          51290 non-null  str
 10  product_id      51290 non-null  str
 11  category        51290 non-null  str
 12  sub_category    51290 non-null  str
 13  product_name    51290 non-null  str
 14  sales           51290 non-null  str
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  str
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), str(16)
memory usage: 8.2 MB

no nulls 

- order date & ship date str type --> convert to datetime 
- sales str type --> convert to int

## Validate and Clean the data

In [ ]:
#converting date str to datetime
df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True)
df['ship_date'] = pd.to_datetime(df['ship_date'], dayfirst=True)
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,2011-01-01,2011-01-05,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [ ]:
#removing comma's for numbers in thousands and converting sales column str to int 
df['sales'] = df['sales'].replace({',':''}, regex=True).astype(int)
df['sales'].dtype

dtype('int64')

In [ ]:
#check for duplicates

In [ ]:
#verify country, market, region

#df['state'].unique()

## Initial stats

In [10]:
df['quantity'].describe()

count    51290.000000
mean         3.476545
std          2.278766
min          1.000000
25%          2.000000
50%          3.000000
75%          5.000000
max         14.000000
Name: quantity, dtype: float64

In [11]:
df['discount'].describe()

count    51290.000000
mean         0.142908
std          0.212280
min          0.000000
25%          0.000000
50%          0.000000
75%          0.200000
max          0.850000
Name: discount, dtype: float64

75% of transactions have a discount of 20% or lower
50% of transactions have no discounta at all 
max discount is much higher at 85% - outlier 
Discount strategy? - not uniformed
relatively small % of orders have a wide range/high of discount values

In [19]:
df['discount'].describe([0.5,0.6,0.7,0.8,0.9,0.95,0.96,0.97,0.98,0.99])

count    51290.000000
mean         0.142908
std          0.212280
min          0.000000
50%          0.000000
60%          0.100000
70%          0.200000
80%          0.350000
90%          0.500000
95%          0.600000
96%          0.700000
97%          0.700000
98%          0.700000
99%          0.700000
max          0.850000
Name: discount, dtype: float64

In [12]:
df['profit'].describe()

count    51290.000000
mean        28.641740
std        174.424113
min      -6599.978000
25%          0.000000
50%          9.240000
75%         36.810000
max       8399.976000
Name: profit, dtype: float64

High standard deviation
significant losses to look at further 
25% transactions making no (or negative) profit 
50% transactions making low profit / median (9.24) is low 
mean (28) > median (9) -skewed
highest profit is well above average 
distribution suggests that small number of high profit transactions may drive the large proportion of profit

In [13]:
df['shipping_cost'].describe()

count    51290.000000
mean        26.375915
std         57.296804
min          0.000000
25%          2.610000
50%          7.790000
75%         24.450000
max        933.570000
Name: shipping_cost, dtype: float64

again mean (26) > median (7) - average is not typical cost 
min of 0 unclear. Could be justified (eg. promotion/included in product price/digital/internal transfer/refunded) or data could be missing
very high max shiping cost, well above majority of orders 
skewed suggesting small no of high freight costs order - exceptions to investigate - destinations/priority type/product type(bulky)?

In [33]:
df['sales'].describe()

count    51290.000000
mean       246.498440
std        487.567175
min          0.000000
25%         31.000000
50%         85.000000
75%        251.000000
max      22638.000000
Name: sales, dtype: float64

## Cleaned dataset

In [ ]:
#save clean data to csv

Cleaned dataset ready for feature engineering