## Read cleaned data

In [1]:
%%bash 

pip install pandas pyarrow

Requirement already satisfied: pandas in /home/slark/DE-projects/Commercial-data/super_store/venv/lib/python3.13/site-packages (3.0.1)
Requirement already satisfied: pyarrow in /home/slark/DE-projects/Commercial-data/super_store/venv/lib/python3.13/site-packages (23.0.1)
Requirement already satisfied: numpy>=1.26.0 in /home/slark/DE-projects/Commercial-data/super_store/venv/lib/python3.13/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/slark/DE-projects/Commercial-data/super_store/venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/slark/DE-projects/Commercial-data/super_store/venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import pyarrow as pa
import os                       
from dotenv import load_dotenv

In [5]:
load_dotenv()

True

In [8]:
data = f"{os.environ['path']}/data/02_clean/01_cleaned_store_data.parquet"

In [5]:
df = pd.read_parquet(data, engine="pyarrow")

In [6]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408.0,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120.0,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,2011-01-01,2011-01-05,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66.0,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45.0,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114.0,5,0.1,37.770,4.70,Medium,2011

In [7]:
df.dtypes

order_id                     str
order_date        datetime64[ns]
ship_date         datetime64[ns]
ship_mode                    str
customer_name                str
segment                      str
state                        str
country                      str
market                       str
region                       str
product_id                   str
category                     str
sub_category                 str
product_name                 str
sales                    float64
quantity                   int64
discount                 float64
profit                   float64
shipping_cost            float64
order_priority               str
year                       int64
dtype: object

# Create State, Region, Market Tables

In [ ]:
df_location = (
    df[['market','region','state']]
    .drop_duplicates()
    .sort_values(['market','region','state'])
    .reset_index(drop=True)
)

#important to reset index for when data will leave pandas 

df_location.head()

  market        region           state
0   APAC  Central Asia  Andhra Pradesh
1   APAC  Central Asia           Assam
2   APAC  Central Asia     Baluchistan
3   APAC  Central Asia           Bihar
4   APAC  Central Asia         Central

In [9]:
%%bash

psql -d superstore

Data ready to be loaded to SQL